In postinst check if i2c bus is enabled
If the i2c bus is not enabled at installation time then update
config.txt to add it and flag that a reboot is needed by touching
/run/reboot-required.

diff --git a/src/config/postinst b/src/config/postinst
--- a/src/config/postinst
+++ b/src/config/postinst
@@ -5,14 +5,54 @@
 #
 
 qw_service="quietwind.weather.service"
-#qw_install_prefix="/usr/local/qw"
-#qw_systemd_service_subdir="systemd/system"
-#qw_service_path="$qw_systemd_service_subdir/$qw_service"
+qw_install_prefix="/usr/local/qw"
+qw_weather_config="etc/ws_config.json"
+qw_weather_config_path="$qw_install_prefix/$qw_weather_config"
+firmware_config_file="/boot/firmware/config.txt"
+need_reboot="false"
+
+#
+# Make sure the I2c bus used by the weather sensors exists
+#
+device_bus=`jq -r '.I2cBus.weather_devices' < $qw_weather_config_path`
+if [ ! -c $device_bus ]; then
+  # The I2C bus doesn't exist so we have to add it to /boot/firmware/config.txt
+  # and then do a reboot before weather station can run
+  need_reboot="true"
+
+  #
+  # Check if there is a line that sets the i2c_arm parameter
+  #
+  if ! grep -q "^\s*dtparam=i2c_arm=on" $firmware_config_file; then
+    
+    # We have to add the dtparam=i2c_arm=on line to the config.txt file
+    # Check if there is a commented out line
+    if grep -q "^.*#.*dtparam=i2c_arm" $firmware_config_file; then
+      #
+      # There is a line for i2c_arm, but it is commented out.
+      # Change the line to remove comment and set to on
+      #
+      sed -i 's/^.*#.*dtparam=i2c_arm.*/dtparam=i2c_arm=on/' $firmware_config_file
+    elif grep -q "^.*dtparam=i2c_arm=off" $firmware_config_file; then
+      #
+      # arm_i2c is specifically set to off. Change the line to set to on
+      #
+      sed -i 's/^.*dtparam=i2c_arm=off.*/dtparam=i2c_arm=on/' $firmware_config_file
+    else
+      #
+      # I2c_arm is not set to off nor is there a commented out line so just add
+      # a line for it
+      # (I am not sure if it can go to the end of the file or not. That might
+      #  put it under category [all] which may be a problem. I am not sure)
+      echo "dtparam=i2c_arm=on" >> $firmware_config_file
+    fi
+  fi
+fi
 
 systemctl daemon-reload
 
 #
-# Check if it is enabled. If not enable it
+# Wether we need to reboot or not Check if it is enabled. If not enable it
 #
 systemctl -q is-enabled $qw_service
 if [ $? -ne 0 ]; then
@@ -20,11 +60,25 @@ if [ $? -ne 0 ]; then
 fi
 
 #
-# Check if it is already running. If not start it
+# If we don't need to reboot to get the I2C bus device go
+# ahead and restart the service.
 #
-systemctl -q is-active $qw_service
-if [ $? -ne 0 ]; then
-  systemctl -q start $qw_service
+if [ $need_reboot = "false" ]; then
+  #
+  # If it is currently running pick up the new version
+  # restart will stop and start a new one if one is running or
+  # start a new one if not
+  # 
+  systemctl -q restart $qw_service
+else
+  #
+  # We need to indicate that a reboot is needed
+  #
+  touch /run/reboot-required
+  # If the package isn't already in the reboot-required.pkgs file then add it
+  if [ ! -f /run/reboot-required.pkgs ] || ! grep -q "qw-weatherstation" /run/reboot-required.pkgs; then
+    echo "qw-weatherstation" >> /run/reboot-required.pkgs
+  fi
 fi
 
 exit 0
